// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "contatos/model"

func Profile(p model.Profile) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-2xl mx-auto bg-white rounded-lg shadow-md p-6 mt-8\"><h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Edit Profile</h1><form method=\"POST\" action=\"/profile\" class=\"space-y-6\"><div><label for=\"first_name\" class=\"block text-sm font-medium text-gray-700\">First Name</label> <input type=\"text\" id=\"first_name\" name=\"first_name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(p.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/profile.templ`, Line: 11, Col: 71}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"mt-1 block w-full rounded-md border-gray-300 px-3 py-2 border\"></div><button type=\"button\" class=\"button-add-data\" onclick=\"addItem()\">add data</button> <datalist id=\"dataTypeList\"><option value=\"Email\"></option> <option value=\"Phone\"></option> <option value=\"Website\"></option> <option value=\"Twitter\"></option> <option value=\"Facebook\"></option> <option value=\"Linkedin\"></option></datalist><ol id=\"data-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for key, value := range p.Data {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"flex gap-2 mb-2\"><input type=\"text\" list=\"dataTypeList\" name=\"custom_key\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(key)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/profile.templ`, Line: 25, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"flex-1 rounded-md border-gray-300 px-3 py-2 border\"> <input type=\"text\" name=\"custom_value\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(value)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/templates/profile.templ`, Line: 26, Col: 58}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" class=\"flex-1 rounded-md border-gray-300 px-3 py-2 border\"></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</ol><button type=\"submit\" class=\"px-6 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 font-medium\">Save Profile</button> <a href=\"/profile\" class=\"px-6 py-2 bg-gray-500 text-white rounded-md hover:bg-gray-600 font-medium ml-2\">Cancel</a></form><template id=\"data-item-template\"><li class=\"flex gap-2 mb-2\"><input type=\"text\" list=\"dataTypeList\" name=\"custom_key\" value=\"\" class=\"flex-1 rounded-md border-gray-300 px-3 py-2 border\"> <input type=\"text\" name=\"custom_value\" value=\"\" class=\"flex-1 rounded-md border-gray-300 px-3 py-2 border\"></li></template><script type=\"text/javascript\">\n\t\tfunction addItem(){\n\t\t    const template = document.getElementById('data-item-template');\n\t\t\tconst clone = template.content.cloneNode(true);\n\t\t\tconst list = document.getElementById('data-list');\n            list.appendChild(clone);\n            return false;\n\t\t}\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
